name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Update to the latest version
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Update to the latest version
      with:
        node-version: '16'  # Use Node.js 16
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
